name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install

      - name: Test
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          component: true
          project: ./packages/react
